### ISSUE TITLE
Erros no cadastro de recursos, símbolos e sinônimos.

### ISSUE THREAD

**Issue by debbybarb** [danvinicius/lexhub#2]
Tivemos dificuldades em adicionar os recursos nos cenários e também na hora de criar um símbolo na hora de inserir o sinônimo e o impacto.

https://github.com/user-attachments/assets/dce10337-7eba-43ec-af70-727358084494

**Comment by danvinicius** [comment]
oi Débora, o comportamento não era um bug, para salvar um item novo no combobox precisa dar 'enter' como é pedido no placeholder pois podem ser adicionados mais de um recurso/impacto/sinônimo/etc, mas realmente não está intuitivo, estou trabalhando para melhorar essa UX, estarei fechando a issue, obrigado pelo feedback!
